<?php
session_start();
if(!isset($_SESSION['usr']) || !isset($_SESSION['pswd'])){
    header("Location: index.php?page=login");
}
?>


<h1>Add Event</h1>

<?php

$session = new app\controllers\DefaultController();
if(isset($_POST['action'] )){

    $session->addEvent();
}
?>

<!--we have our html form here where user information will be entered-->
<form action='#' method='post' border='0'>
    <table>
        <tr>
            <td>Name Of Event</td>
            <td><input type='text' name='eventname' /></td>
        </tr>
        <tr>
            <td>Location Of Event</td>
            <td><input type='text' name='eventlocation' /></td>
        </tr>
        <tr>
            <td>Date Of Event</td>
            <td><input type='text' name='eventdate' /></td>
        </tr>

        <td><input type='hidden' name='action' value='create' />
            <input type='submit' value='Save' />
        </td>
        <td>


            <a href='index.php?page=admin'>Back to admin</a>
        </td>
        </tr>
    </table>
</form>

</body>
</html>