<?php
session_start();
if(!isset($_SESSION['usr']) || !isset($_SESSION['pswd'])){
    header("Location: index.php?page=login");
}
?>


<h1>Add Squad Member</h1>

<?php

$session = new app\controllers\DefaultController();
if(isset($_POST['action'] )){

    $session->addSquad();
}

?>

<!--we have our html form here where user information will be entered-->
<form action='#' method='post' border='0'>
    <table>
        <tr>
            <td>Name of Member</td>
            <td><input type='text' name='squadname' /></td>
        </tr>
        <tr>
            <td>Member Picture</td>
            <td><input type='text' name='squadpicture' /></td>
        </tr>
        <tr>
            <td>Date of Birth</td>
            <td><input type='text' name='squaddob' /></td>
        </tr>
        <tr>
            <td>Member Bio</td>
            <td><input type='text' name='squadbio' /></td>
        </tr>
        <tr>
            <td>Team</td>
            <td><select name="squadteam">
                    <option value="First Team">First Team</option>
                    <option value="Second Team">Development Team</option>

                </select></td>
        </tr>

        <td><input type='hidden' name='action' value='create' />
            <input type='submit' value='Save' />
        </td>
        <td>


            <a href='index.php?page=admin'>Back to admin</a>
        </td>
        </tr>
    </table>
</form>

<script>
    if (!Modernizr.inputtypes.date) {
        $('input[type=date]').datepicker({
            // Consistent format with the HTML5 picker
            dateFormat: 'dd/mm/yy'
        });
    }</script>
