<?php

session_start();
if(!isset($_SESSION['usr']) || !isset($_SESSION['pswd'])){
    header("Location: index.php?page=login");
}

$session = new app\controllers\DefaultController();
$session->updateSquad($_GET['id']);

?>

<script>
    if (!Modernizr.inputtypes.date) {
        $('input[type=date]').datepicker({
            // Consistent format with the HTML5 picker
            dateFormat: 'dd/mm/yy'
        });
    }</script>