<h2>About Us</h2>

<p>
    Our club was formed in 1974 and we are most probably one of the oldest clubs around in the UK today.
    To this day we are still one of the biggest clubs in the country and currently take 2 teams to national
    competitions, meaning anyone and everyone can take part. We have a large range of members within our club,
    including some who have been there from the very beginning. There are a large number of social club players
    and we also have a very good number of competitive players, with several active players having played at the
    highest elite international level. The squad has 5 of its members representing Great Britain at the CMAS World
    Championships in August 2013.
</p>


<h2>Squad</h2>
<img src="images/squad/westWickhamSquad" alt="Team Photo of Squad">
<p><em> Elite Squad 2014 Semi Finals (Leeds) </br>
        Scott Henderson, Karl Speed, Jason Glass, Dess Mathewman, Andrew Burns, Matt Nunn </br>
        Pete Hodge, Joss Greenhal, Rob Howard, Turlough Remedios, Scott Allen, Chris Alwin</em></p>
