<h2>About Us</h2>

<p>
    Our club was formed in 1974 and we are most probably one of the oldest clubs around in the UK today.
    To this day we are still one of the biggest clubs in the country and currently take 2 teams to national
    competitions, meaning anyone and everyone can take part. We have a large range of members within our club,
    including some who have been there from the very beginning. There are a large number of social club players
    and we also have a very good number of competitive players, with several active players having played at the
    highest elite international level. The squad has 5 of its members representing Great Britain at the CMAS World
    Championships in August 2013.
</p>

<div id="squad">
<h2>Squad</h2>
<img src="images/squad/westWickhamSquad" alt="Team Photo of Squad">
<p><em> Elite Squad 2014 Semi Finals (Leeds) </br>
        Scott Henderson, Karl Speed, Jason Glass, Dess Mathewman, Andrew Burns, Matt Nunn </br>
        Pete Hodge, Joss Greenhal, Rob Howard, Turlough Remedios, Scott Allen, Chris Alwin</em></p>

    </div>

<div id="press">

    <section class="col-2">

        <h2>West Wickham in the Press</h2>
        <a href="images/news/Kent%20On%20Saturday%20(4-Aug)%20Feature%20Story.png"><img src="images/news/Kent%20On%20Saturday%20(4-Aug)%20Feature%20Story.png"></a>
        <p>Bacon ipsum dolor sit amet sirloin ribeye turkey drumstick pastrami leberkas, ham short ribs. Leberkas
            pastrami tenderloin, pork belly prosciutto kevin t-bone sausage chicken capicola bacon. Tail shankle short
            loin shoulder pancetta turducken shank. Jerky landjaeger corned beef, kielbasa pork belly short ribs leberkas
            biltong bacon rump ribeye sausage. Short loin ball tip porchetta shoulder, prosciutto t-bone capicola.</p>

    </section>





<section class="col-3">
    <h2>Underwater Hockey Videos </h2>

    <div id="uwhvideos">

        <iframe width="640" height="360" src="//www.youtube.com/embed/ZyksmpQ203E" frameborder="0" allowfullscreen></iframe>

        <iframe src="//player.vimeo.com/video/38617121" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>
    <div id="uwhlinks">
        <a href="http://vimeo.com/38617121">Video 1</a>
        <a href="http://youtu.be/ZyksmpQ203E">Video 2</a>
    </div>


</section>
</div>