

<div id="contact_form">

    <h2>Contact Form</h2>

    <?php
    $session = new app\controllers\DefaultController();
    if(isset($_POST['action'] )){

        $session->westwickhamEmail();
        echo "<h2>Thanks</h2>";
    }
    ?>




    <form class="form" method="POST" action="index.php?page=contact" id="contact-form">

        <p class="name">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" placeholder="Name" required="" />

        </p>

        <p class="email">
            <label for="email">Email</label>
            <input type="text" name="email" id="email" placeholder="mail@example.com" required="" />

        </p>

        <p class="text">
            <textarea rows="10" cols="55" name="comment" placeholder="Write A Message To Us" required=""></textarea>
        </p>

        <p class="submit">
            <input type="submit" name="action" value="Send" />
        </p>
    </form>

</div>