<div id="contact_form">

    <h2>Contact Form</h2>

    <form class="form" method="get" action="http://webdesignstudents.co.uk/students/response.php">

        <p class="name">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" placeholder="John Smith" />

        </p>

        <p class="email">
            <label for="email">Email</label>
            <input type="text" name="email" id="email" placeholder="mail@example.com" />

        </p>

        <p class="text">
            <textarea rows="10" cols="55" name="text" placeholder="Write A Message To Us"></textarea>
        </p>

        <p class="submit">
            <input type="submit" value="Send" />
        </p>
    </form>

</div>