<p>Here we have a list of event that are taking place in the foreseeable future</p><br>


<?php
//include database connection
//include 'connect.php';
//include('../app/controllers/DefaultController.php');
$session = new app\controllers\DefaultController();

$session->viewEvent();
/*$action = isset($_GET['action']) ? $_GET['action'] : "";


//select all data
$query = "SELECT * FROM events";
$stmt = $con->prepare( $query );
$stmt->execute();

//this is how to get number of rows returned
$num = $stmt->rowCount();




$num = $stmt->rowCount();


if($num>0){ //check if more than 0 record found

    echo "<table border='1'>";//start table

    //creating our table heading
    echo "<tr>";
    echo "<th>Event</th>";
    echo "<th>Date</th>";
    echo "<th>Location</th>";
    //echo "<th>Action</th>";
    echo "</tr>";

    //retrieve our table contents
    //fetch() is faster than fetchAll()
    //http://stackoverflow.com/questions/2770630/pdofetchall-vs-pdofetch-in-a-loop
    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)){
        //extract row
        //this will make $row['firstname'] to
        //just $firstname only
        extract($row);

        //creating new table row per record
        echo "<tr>";
        echo "<td>{$eventname}</td>";
        echo "<td>{$eventdate}</td>";
        echo "<td>{$eventlocation}</td>";

        echo "</tr>";
    }

    //end table
    echo "</table>";

}

//if no records found
else{
    echo "No records found.";
}

?>
*/


