<div class="cycle-slideshow">
    <img src="images/home/slider/image1-slider.jpg" alt="Scott and Matt on the Puck">
    <img src="images/home/slider/image2-slider" alt="GB girls TEAM Airplane">

</div>

<div id="intro">
    <h2>Who we are</h2>
    <p>Welcome to the homepage of West Wickham Underwater Hockey Club.  We currently train twice a week Monday and Thursday in the South London area,
        with our Thursday night session being one of the biggest in London and running two seperate games.  After every session we of course then
        head on down to the local pub.</p>


    <p>Anyone is welcome to just come along, and all levels of experience are catered for. The first time you play with us is free but everytime
        after that it's normally £6 per guest session. Once you become a member of the club you have the opportunity to pay over longer periods to
        make greater savings. Juniors may attend our adult sessions for free.</p>
</div>

<div class="col-3">
    <h2>Latest from Facebook</h2>

    <section class="fb-post">
        <div class="fb-title">
            <h3>First Title</h3>
        </div>
        <div class="fb-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra, felis et congue dignissim, diam metus cursus diam, mattis molestie purus quam
                sit amet purus. Aliquam sit amet massa at neque varius mattis scelerisque ut lacus. Suspendisse egestas porttitor felis sit amet tempor. Quisque venenatis
                nisi eu orci ullamcorper, quis consequat nisl vehicula. Curabitur placerat urna vel velit eleifend, et.</p>
        </div>
    </section>
    <section class="fb-post">
        <div class="fb-title">
            <h3>Second Title</h3>
        </div>
        <div class="fb-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra, felis et congue dignissim, diam metus cursus diam, mattis molestie purus quam
                sit amet purus. Aliquam sit amet massa at neque varius mattis scelerisque ut lacus. Suspendisse egestas porttitor felis sit amet tempor. Quisque venenatis
                nisi eu orci ullamcorper, quis consequat nisl vehicula. Curabitur placerat urna vel velit eleifend, et.</p>
        </div>
    </section>
    <section class="fb-post">
        <div class="fb-title">
            <h3>Third Title</h3>
        </div>
        <div class="fb-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra, felis et congue dignissim, diam metus cursus diam, mattis molestie purus quam
                sit amet purus. Aliquam sit amet massa at neque varius mattis scelerisque ut lacus. Suspendisse egestas porttitor felis sit amet tempor. Quisque venenatis
                nisi eu orci ullamcorper, quis consequat nisl vehicula. Curabitur placerat urna vel velit eleifend, et.</p>
        </div>
    </section>
</div>