<div class="cycle-slideshow">
    <img src="images/home/slider/image1-slider.jpg" alt="Scott and Matt on the Puck">
    <img src="images/home/slider/image2-slider" alt="GB girls TEAM Airplane">

</div>

<div id="intro">
    <h2>Who we are</h2>
    <p>Welcome to the homepage of West Wickham Underwater Hockey Club.  We currently train twice a week Monday and Thursday in the South London area,
        with our Thursday night session being one of the biggest in London and running two seperate games.  After every session we of course then
        head on down to the local pub.</p>


    <p>Anyone is welcome to just come along, and all levels of experience are catered for. The first time you play with us is free but everytime
        after that it's normally £6 per guest session. Once you become a member of the club you have the opportunity to pay over longer periods to
        make greater savings. Juniors may attend our adult sessions for free.</p>
</div>

<div class="col-3">
    <div id="FeederNinja_cebe8acd529d458b89f025e2754ef2e8"></div>
    <script type="text/javascript">
        (function() {
            var fn = document.createElement('script'); fn.type = 'text/javascript';
            fn.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'feederninja.com/api/feed/cebe8acd529d458b89f025e2754ef2e8?fnurl=' + window.location.href;
            var s = document.getElementsByTagName('head')[0].appendChild(fn);
        })();
    </script>
</div>