<?php
session_start();
if(isset($_SESSION['usr']) && isset($_SESSION['pswd'])){
    header("Location: index.php?page=admin");
}
?>


    <style>
        body {
            background-color: #29366f;
        }
        body header {
            display: none;
        }
        body #page {
            width: 327px;
            margin: 0 auto;
        }
        #content {
            display: block;
            margin: 0 auto;
            width: 327px;
        }
        #content img {
            max-width: 327px;
            width: 100%;
            display: block;
            margin: 0 auto;
        }
        body #page #content #contact_form form p input {
            display: block;
            width: 300px;

            margin: 0 auto;
        }
        body #page #content #contact_form form .submit input {
            background-color: #1D264D;
        }

    </style>

</head>
<body onload="junior_page()">
<div id="page">

    <div id="content">

        <a href="index.php?page=home"><img src="images/home/West%20Wickham_mens%20suit%20V2.jpg"></a>
        <div id="contact_form">
            <form id="login" name="login" method="post" action="checklogin.php" >
                <p class="username">
                    <input type="text" name="usr" id="myusername" placeholder="User Name" />
                </p>

                <p class="password">
                    <input type="password" name="pswd" id="mypassword" placeholder="Password" />
                </p>
                <p class="submit">
                    <input type="submit" value="Login" name="login" />
                </p>
            </form>
        </div>





    </div>

    <footer>

    </footer>

</div><!--End of Page ID-->



</body>
