<div id="news">

    <section class="col-2">

        <h2>West Wickham in the Press</h2>
        <a href="images/news/Kent%20On%20Saturday%20(4-Aug)%20Feature%20Story.png"><img src="images/news/Kent%20On%20Saturday%20(4-Aug)%20Feature%20Story.png"></a>
        <p>Bacon ipsum dolor sit amet sirloin ribeye turkey drumstick pastrami leberkas, ham short ribs. Leberkas
            pastrami tenderloin, pork belly prosciutto kevin t-bone sausage chicken capicola bacon. Tail shankle short
            loin shoulder pancetta turducken shank. Jerky landjaeger corned beef, kielbasa pork belly short ribs leberkas
            biltong bacon rump ribeye sausage. Short loin ball tip porchetta shoulder, prosciutto t-bone capicola.</p>

    </section>

    <section class="col-3">
        <h2>Underwater Hockey Videos </h2>

        <div id="uwhvideos">

            <iframe width="640" height="360" src="//www.youtube.com/embed/ZyksmpQ203E" frameborder="0" allowfullscreen></iframe>

            <iframe src="//player.vimeo.com/video/38617121" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
        <div id="uwhlinks">
            <a href="http://vimeo.com/38617121">Video 1</a>
            <a href="http://youtu.be/ZyksmpQ203E">Video 2</a>
        </div>


    </section>

</div>