<div class="col-1">

    <section class="fb-post">
        <div class="fb-title">
            <h3>First</h3>
        </div>
        <div class="fb-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra, felis et congue dignissim, diam metus cursus diam, mattis molestie purus quam
                sit amet purus. Aliquam sit amet massa at neque varius mattis scelerisque ut lacus. Suspendisse egestas porttitor felis sit amet tempor. Quisque venenatis
                nisi eu orci ullamcorper, quis consequat nisl vehicula. Curabitur placerat urna vel velit eleifend, et.</p>
        </div>
    </section>

</div>


<div class="col-2">
    <section class="fb-post">
        <div class="fb-title">
            <h3>Second Title</h3>
        </div>
        <div class="fb-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra, felis et congue dignissim, diam metus cursus diam, mattis molestie purus quam
                sit amet purus. Aliquam sit amet massa at neque varius mattis scelerisque ut lacus. Suspendisse egestas porttitor felis sit amet tempor. Quisque venenatis
                nisi eu orci ullamcorper, quis consequat nisl vehicula. Curabitur placerat urna vel velit eleifend, et.</p>
        </div>
    </section>
    <section class="fb-post">
        <div class="fb-title">
            <h3>Third Title</h3>
        </div>
        <div class="fb-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra, felis et congue dignissim, diam metus cursus diam, mattis molestie purus quam
                sit amet purus. Aliquam sit amet massa at neque varius mattis scelerisque ut lacus. Suspendisse egestas porttitor felis sit amet tempor. Quisque venenatis
                nisi eu orci ullamcorper, quis consequat nisl vehicula. Curabitur placerat urna vel velit eleifend, et.</p>
        </div>
    </section>


</div>



<div class="col-3">


    <section class="fb-post">
        <div class="fb-title">
            <h3>Fourth title</h3>
        </div>
        <div class="fb-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra, felis et congue dignissim, diam metus cursus diam, mattis molestie purus quam
                sit amet purus. Aliquam sit amet massa at neque varius mattis scelerisque ut lacus. Suspendisse egestas porttitor felis sit amet tempor. Quisque venenatis
                nisi eu orci ullamcorper, quis consequat nisl vehicula. Curabitur placerat urna vel velit eleifend, et.</p>
        </div>
    </section>
    <section class="fb-post">
        <div class="fb-title">
            <h3>Fifth title</h3>
        </div>
        <div class="fb-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra, felis et congue dignissim, diam metus cursus diam, mattis molestie purus quam
                sit amet purus. Aliquam sit amet massa at neque varius mattis scelerisque ut lacus. Suspendisse egestas porttitor felis sit amet tempor. Quisque venenatis
                nisi eu orci ullamcorper, quis consequat nisl vehicula. Curabitur placerat urna vel velit eleifend, et.</p>
        </div>
    </section>
    <section class="fb-post">
        <div class="fb-title">
            <h3>Sixth title</h3>
        </div>
        <div class="fb-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra, felis et congue dignissim, diam metus cursus diam, mattis molestie purus quam
                sit amet purus. Aliquam sit amet massa at neque varius mattis scelerisque ut lacus. Suspendisse egestas porttitor felis sit amet tempor. Quisque venenatis
                nisi eu orci ullamcorper, quis consequat nisl vehicula. Curabitur placerat urna vel velit eleifend, et.</p>
        </div>
    </section>




