<h2>Squad</h2>

<form name="Squad" action="" method="POST">
    <div align="center">
        <select name="squadlist">
            <option value="firstTeam">First Team</option>
            <option value="secondTeam">Development Team</option>
            <option value="all">All Members</option>
        </select>
    </div>
</form>

<?php

$session = new app\controllers\DefaultController();

$session->viewSquad();


?>