
<h2>Squad</h2>

<!--<form name="Squad" action="#" method="POST">
    <div align="center">
        <select name="squadlist" id="url" >
            <option value="all">All Members</option>
            <option value="firstTeam">First Team</option>
            <option value="secondTeam">Development Team</option>

        </select>
    </div>
</form>-->


<?php

$session = new app\controllers\DefaultController();

$session->viewSquad();


?>