<h1>Terms and Conditions ("Terms")</h1>
<p>Last updated: June 13, 2014</p>

<p>Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the webdesignstudents.co.uk/students/chris/ website (the "Service") operated by West Wickham Underwater Hockey ("us", "we", or "our").</p>

<p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service.</p>

<p>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.</p>


<p><strong>Links To Other Web Sites</strong></p>

<p>Our Service may contain links to third-party web sites or services that are not owned or controlled by West Wickham Underwater Hockey.</p>

<p>WestWickham Underwater Hockey has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that WestWickham Underwater Hockey shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.</p>

<p>We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.</p>

<p><strong>Termination</strong></p>

<p>We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>

<p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>

<p><strong>Images</strong></p>
<p>All Images on this website are used with permission or owned by West Wickham Underwater Hockey club. Any Violation of this will result in legal action.</p>


<p><strong>Governing Law</strong></p>

<p>These Terms shall be governed and construed in accordance with the laws of United Kingdom, without regard to its conflict of law provisions and excluding the United Nations Convention on Contracts for the International Sale of Goods (CISG).</p>

<p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.</p>

<p><strong>Changes</strong></p>

<p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>

<p>By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.</p>

<p>Generated with permission from <a href="http://termsfeed.com/" title="TermsFeed" style="color: #999; text-decoration: none;">TermsFeed</a></p>

<p><strong>Contact Us</strong></p>

<p>If you have any questions about these Terms, please contact us.</p>